### ISSUE TITLE
10.0 Construir un módulo para facturación electrónica con validación previa (l10n_co_e_invoicing)

### ISSUE THREAD

**Issue by lauracvilla-zz** [odoo-colombia/l10n-colombia#10]
Se requiere el desarrollo de un módulo para la facturación electrónica con validación previa. (Este es el módulo de facturación ensí, por lo que los camposo descritos abajo son el primer borrador que se irá complementando a medida que el desarrollo avance:

**Nombre propuesto:**
l10n_co_e_invoicing

**CAMPOS:**
- [ ] **NP:** qr_code | Modelo: dian.document | Sección Anexo: 10.3 | Guía: 
- [x]  **NP:** test_set_id | Modelo: res.company | Sección Anexo: 11.9 | Campo nuevo para validacion previa
- [x]  **NP:** profile_execution_id | Modelo:  res.company | Sección Anexo: 6.1.1 | Campo nuevo de validación previa. Etiquetas: cbc:ProfileExecutionID y cbc:UUID.@schemeID
- [x]  **NP:** track_id | Modelo: dian.document |  Sección Anexo: 6.1.2, 10 | Valor correspondiente con el CUFE, se encuentra en los xml como UUID, y en otros como TrackId
- [x]  **NP:**  software_pin | Modelo: res.company | Sección Anexo: 6.1.2, 10 | La base del modulo es [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice), haciendo los cambios correspondientes.
- [x]  **NP:**  technical_key | Modelo: ir.sequence.date_range | Sección Anexo: 6.1.2, 10.2, 10 | La base del modulo es [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice), haciendo los cambios correspondientes.
- [ ]  **NP:**  dian_document_ids |  Modelo: account.invoice | Campo para relacionar solicitudes a la Dian con la factura, podrian existir  varias, ya que pueden resultar solucitudes rechazadas, que no se necesitan modificar y sirven de historial, se debe crear una nueva solicitud con las correcciones hasta que sea validada correctamente
- [ ]  **NP:**  type |  Modelo: account.invoice | El campo type, nos indica que el valor "out_refund" es una nota crédito
- [ ]  **NP:** is_export_invoice |  Modelo: account.invoice | En las facturas de proveedor hay que saber cuando es una factura de exportacion, se debe realizar el proceso correspondiente con ese tipo de facturas
- [ ]  **NP:** invoice_note |  Modelo:  account.invoice | El valor correspondiente a la etiqueta <cbc:Note>
- [ ]  **NP:** invoice_id | Modelo:  dian.document |  Se deben relacionar solicitudes a la Dian con la factura, podrian haber varias ya que pueden resultar solucitudes rechazadas, que no se necesitan modificar y sirven de historial, se debe crear una nueva solicitud con las correcciones hasta que sea validada correctamente.
- [ ]  **NP:** validation_response_name |  Modelo:  dian.document | En el modulo [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice) el campo response_document_dian tiene una lista de posibles mensajes recibidos, tanto como para errores como para ejecuciones exitosas, se debe consultar para ver si se reciben los mismo mensajes; podria ser muy útil a la hora de cambios de la Dian que podamos recibir cualquier error, y almacenar, el código y el mensaje, si se elige tener la lista fija de errores, shipping_response_code y shipping_response_name se deben volver solo un campo "shipping_response"
- [ ]  **NP:** validation_response_code |   Modelo:  dian.document | En el modulo [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice) el campo response_document_dian tiene una lista de posibles mensajes recibidos, tanto como para errores como para ejecuciones exitosas, habria que averiguar si recibiriamos los mismo mensajes. aunque podria ser mas util a la hora de cambios de la dian que podamos recibir cualquier error, y almacenar, el codigo y el mensaje, si se elige tener la lista fija de errores, validation_response_code y validation_response_name se deben volver solo un campo "validation_response"
- [ ]  **NP:** shipping_response_code |    Modelo:  dian.document |  En el modulo [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice) el campo shipping_response tiene una lista de posibles mensajes recibidos, tanto como para errores como para ejecuciones exitosas, se debe consultar para ver si se reciben los mismo mensajes; podria ser muy útil a la hora de cambios de la Dian que podamos recibir cualquier error, y almacenar, el código y el mensaje, si se elige tener la lista fija de errores, shipping_response_code y shipping_response_name se deben volver solo un campo "shipping_response"
- [ ]  **NP:** shipping_response_name |  Modelo:  dian.document | En el modulo [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice) el campo shipping_response tiene una lista de posibles mensajes recibidos, tanto como para errores como para ejecuciones exitosas, se debe consultar para ver si se reciben los mismo mensajes; podria ser muy útil a la hora de cambios de la Dian que podamos recibir cualquier error, y almacenar, el código y el mensaje, si se elige tener la lista fija de errores, shipping_response_code y shipping_response_name se deben volver solo un campo "shipping_response"
- [ ]  **NP:** send_date |   Modelo: dian.document |  Para la fecha de envio de la solicitud, lo más seguro es que no haya mucha diferencia entre la fecha de envio y la de validación, pero es bueno saber, cual es el tiempo transcurrido entre el envío y la validación, asi sean segundos. Y para contingencias en la transmisión estos tiempos pueden ser distintos.
- [ ]  **NP:**  validation_date |  Modelo: dian.document |Para la fecha de validación en la que se recibe la aprobación por la Dian, lo más seguro es que no haya mucha diferencia entre la fecha de envio y la de validación, pero es bueno saber, cual es el tiempo transcurrido entre el envio y la validacion, asi sean segundos. Y para contingencias en la transmisión estos tiempos pueden ser distintos.
- [ ]  **NP:** file_name_sent |  Modelo: dian.document | Nombre del archivo que se envio a la dian
- [ ]  **NP:**  file_name_received | Modelo:  dian.document | Nombre del archivo que se recibio de a la dian
- [x]  **NP:** state |  Modelo: dian.document | Se debe revisar el módulo y complementar [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice) 
- [ ]  **NP:** type | Modelo:  dian.document | Tipo de solicitud, ej: invoice, credit note, etc
- [x]  **NP:** certificate_password | Modelo: res.company | Requerido para módulo
- [x]  **NP:** sotfware_id | Modelo: res.company | Se debe tener el campo para el valor de la etiqueta <sts:SoftwareID> de los xml
- [ ]  **NP:**  files_path | Modelo: res.company | El módulo [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice)  funciona con la ruta donde se almacenan los diferentes tipos de archivos que se envian y los que se reciben de la DIAN. 
- [ ]  **NP:** certificate_path |  Modelo: res.company |  En el módulo [l10n_co_e-invoice](https://github.com/dkrimmer84/l10n_co_e-invoice)  funciona con la ruta, lo que hace que un paso de configuracion sea almacenar el certificado en una ruta que se establezca en este campo, otra opción es cambiar el campo a certificate_file de tipo binario donde se cargue el archivo desde el campo.
- [ ]  **NP:** email_einvoice |  Modelo: res.company | Posiblemente haya que establecer un correo desde donde se envien los correos correspondientes con facturación electrónica, que podría ser diferente al configurado para tareas normales
- [ ]  **NP:** email_einvoice | Modelo: res.partner | El correo lo tiene almacenado ya el campo email del tercero, es bueno tener en cuenta si tal vez tengamos que tener un correo almacenado solo para envío de correos de facturación electrónica.

**Comment by hivam** [comment]
Excelente trabajo @lauracvilla 

Si el objetivo es postular el módulo para evaluación de OCA hay un pequeño detalle que se debe tener en cuenta , ya existen los módulos que generan la factura electrónica con estándar ubl 2.1:

[https://www.odoo.com/apps/modules/12.0/account_invoice_ubl/](url)
 
Así que el punto de partida para la localización Colombia deberían ser esos módulos.

Saludos

**Comment by lauracvilla-zz** [comment]
Gracias @hivam 
Todos estos aportes son bienvenidos. @JoanMarin por favor revisa la información que comparte Héctor para incluirla.

**Comment by baenacc** [comment]
Hola a todos, me gustaría poder colaborar con el proyecto.
¿Que significa NP? ¿Ya está funcionando este modulo en alguna empresa?

**Comment by JoanMarin** [comment]
@baenacc 
> Hola a todos, me gustaría poder colaborar con el proyecto.
> ¿Que significa NP? 

Creo que significa **Nombre Propuesto**
Realmente esta lista de pendientes esta desactualizada, o los nombres de los campos cambiaron o se hizo de otra forma pero el modulo se finalizo la primera semana de Enero del 2020, para que funcionara en general (hay cosas que no incluimos aun, por que no nos aplicaban como por ejemplo empresas tipo consorcio, pero se dejaron en el código de los **XML's** esos **TODO** por si acaso alguien necesita revisar esos apartados, pero se podría decir que para el 80-90% de empresas seria compatible), actualmente hay que cambiar o agregar nuevas cosas de las nuevas resoluciones de la DIAN pero como esta, es funcional. Entraremos a revisar unos cambios que entraran en vigencia el 1ero de agosto estas próximas 2 semanas.
> ¿Ya está funcionando este modulo en alguna empresa?

Si, ya esta funcionando para varias empresas en versión 10.0, solo necesitas un Certificado para Firma Digital y configurar el modulo.
En el README de este modulo [10.0/l10n_co_account_e_invoicing/README.rst](https://github.com/odooloco/l10n-colombia/blob/10.0/l10n_co_account_e_invoicing/README.rst), que es modulo principal, mas o menos guía en como hacerlo, obviamente debes haber interactuado con el sistema de la DIAN para entender y obtener la información necesitas para esos campos.
[Habilitación y/o Pruebas](https://catalogo-vpfe-hab.dian.gov.co/)
[Producción](https://catalogo-vpfe.dian.gov.co/)
