### ISSUE TITLE
Como recuperar la información fiscal previa a la instalación del modulo

### ISSUE THREAD

**Issue by jescobarv-git** [odoo-colombia/l10n-colombia#28]
Antes de instalar el modulo se tiene la informacion fiscal del cada contacto asi:

![image](https://user-images.githubusercontent.com/61430982/78850285-6e637800-79dc-11ea-87d3-aeb639f5fc74.png)

Despues de instalar el modulo se pierde esta información

![image](https://user-images.githubusercontent.com/61430982/78850316-86d39280-79dc-11ea-9b5b-31aac6a3b428.png)

![image](https://user-images.githubusercontent.com/61430982/78850370-aa96d880-79dc-11ea-9aae-2956732be49c.png)

Por favor su ayuda para recuperar los NIT de los contactos ingresados antes de la instalacion.

**Comment by JoanMarin** [comment]
Esto requiere algo mas de conocimientos técnicos.

El campo **TIN** que mencionas técnicamente se llama **vat**
El campo **Identification Document** técnicamente se llama **identification_document**
El campo **Verification Digit** técnicamente se llama **check_digit**

El campo **vat** simplemente se oculto de la vista pero sigue con la información que tenia previa a la instalación del modulo **l10n_co_partner_vat**, y lo que hacen estos dos nuevos campos (**identification_document** y **check_digit**) es llenar el campo **vat**, con la estructura correcta de país mas documento

La solución es realizar una consulta SQL que pase la información del campo vat a los campos **identification_document** y **check_digit** pero tu caso es muy particular por ustedes guardaban en el mismo campo el tipo de documento, y el sistema no les ponía problema porque NI corresponde al codigo **ISO 3166-1 alfa-2** de Nicaragua, y pues para este país no hay ninguna validación de documento en el Odoo.

Y el campo **vat** lo que se debe guardar son los 2 caracteres que representan el país (**ISO 3166-1 alfa-2**) mas el documento. En el caso de **Colombia** es **CO**, digamos otro caso seria **Estados Unidos de América** que su código **ISO 3166-1 alfa-2** es **US**, estos dos caracteres los utiliza el Odoo para hacer una validación al documento según el país, en el caso de Colombia solo se hace una validación si el tipo de documento es un NIT, y lo que valida es que el dígito de verificación si corresponda al documento. Con el resto de documentos no se hace ninguna validación por ahora y el dígito de verificación no es requerido con los otros tipos de documento.

Yo propondría las siguientes consultas para dar una idea de lo que se tendría que hacer para organizar tu base de datos

UPDATE RES_PARTNER
SET identification_document = SUBSTRING(vat, 5, 10), check_digit = SUBSTRING(vat, 14)
WHERE vat LIKE 'NIT.%';

UPDATE RES_PARTNER
SET identification_document = SUBSTRING(vat, 4)
WHERE vat LIKE 'CC.%';

UPDATE RES_PARTNER
SET vat = 'CO'||SUBSTRING(vat, 5)
WHERE vat LIKE 'NIT.%';

UPDATE RES_PARTNER
SET vat = SUBSTRING(vat, 4)
WHERE vat LIKE 'CC.%';
