### ISSUE TITLE
10.0 Construir módulo para responsabilidades fiscales (l10n_co_partner_tax_level_code)

### ISSUE THREAD

**Issue by lauracvilla-zz** [odoo-colombia/l10n-colombia#3]
Hola @camilozuluaga  y @BrayhanJC 
Tal como hablamos ahora la idea es que empecemos a documentar y realizar las mejoras a los módulos que hemos propuesto y faltantes para reemplazar el l10n_co_res_partner para tener este módulo en recomendaciones OCA.

Para reemplazarlo totalmente hace falta:
1. Agregar un tipo a las posiciones fiscales "tipo DIAN" a las posiciones fiscales:

Inicialmente estaba así en el módulo:

 # Tributate regime
    x_pn_retri = fields.Selection(
        [
            (6, "Simplified"),
            (23, "Natural Person"),
            (7, "Common"),
            (11, "Great Taxpayer Autorretenedor"),
            (22, "International"),
            (25, "Common Autorretenedor"),
            (24, "Great Contributor")
        ], "Tax Regime"

    )

Pero en el anexo técnico, página 230, numeral 6.2.7 aparecen otras responsabilidades fiscales y la semana pasada la DIAN publicó esta información:

https://www.dian.gov.co/Paginas/Conozca-las-nuevas-responsabilidades-que-la-DIAN-ha-dispuesto-en-el-Rut-con-ocasion-de-la-ley-de-financiamiento.aspx

@hivam  requerimos de tu apoyo contable para que nos ayudes a validar si la facturación electrónica con validación previa, debe incluir estos cambios indicados por la DIAN la semana pasada, ya que modifican información del anexo técnico.

[Anexo tcnico de factura electr¢nica de venta.pdf](https://github.com/odooloco/l10n-colombia/files/3581416/Anexo.t.cnico.de.factura.electr.nica.de.venta.pdf)

**Comment by lauracvilla-zz** [comment]
Hola,
@camilozuluaga, @BrayhanJC  y @hivam 

Hoy realicé una llamada a la DIAN y me confirmaron que la semana pasada realizaron una actualización al anexo técnico incluyendo la información de la noticia que les puse arriba:

Para descargar los archivos actualizados  entrar por:
https://factura-electronica.dian.gov.co/videos-cartillas-17.html

Y descargar la caja de herramientas:

![imagen](https://user-images.githubusercontent.com/38291377/64812241-6f2a4d80-d564-11e9-9149-2a1b5fbbe181.png)

Está actualizado a Septiembre 6/2019

Con esto ya estaría actualizada la información requerida para el módulo.

**Comment by lauracvilla** [comment]
Hola, en este caso es necesario realizar el módulo propuesto: 
**Módulo:** l10n_co_account_position_list_name
**Campo(s):** accoun.position.fiscal
**Modelo:** accoun.position.fiscal

Información detallada:
Punto 6.2.4 del anexo tecnico DIAN

**Comment by hivam** [comment]
En mi opinión no es buena práctica hacer un módulo independiente para agregar un campo, máxime cuándo no agrega ningún valor funcional si no que se adiciona solo para cumplir un requisito legal.

Así que mi recomendación es optar por una de estas dos alternativas:

- Modificar el módulo l10n_co_res_partner, o el que lo vaya a reemplazar, actualizando la lista de valores posibles en el campo tipo select.

- Eliminar el campo del módulo l10n_co_res_partner, o el que lo vaya a reemplazar, y agregarlo en el módulo de facturación electrónica

**Comment by hivam** [comment]
En Odoo v12 Enterprise el campo se agrega en el módulo Facturación electrónica:

[https://www.odoo.com/documentation/user/12.0/accounting/localizations/colombia.html#configuration](url)

Ver **4.1.2 Fiscal structure (RUT)**.
Para el campo **Obligaciones y Responsabilidades** usan el tipo Many2many, así es más fácil de mantener hacia futuro, si la DIAN crea nuevas responsabilidades basta con agregarlas al modelo relacionado sin tener que modificar el código.

**Comment by JoanMarin** [comment]
> En mi opinión no es buena práctica hacer un módulo independiente para agregar un campo, máxime cuándo no agrega ningún valor funcional si no que se adiciona solo para cumplir un requisito legal.

@hivam : Respetamos tu opinión y hace algunos años la hubiésemos compartido, pero estos últimos años que hemos venido implementado Odoo de una forma más ordenada y adquiriendo la metodología como la OCA trabaja, la cual consiste en realizar módulos atomizados, que permiten mantenibilidad de forma fácil y eficiente, ya que a la hora de corregir un error o realizar una mejora, siendo redundantes es más fácil y eficiente realizar esta tarea, además de que esa atomicidad permite crear nuevos módulos que incluyan como dependencias los módulos ya previamente desarrollados, incluyendo en el nuevo módulo solo la parte que complementa a la existente.

> Así que mi recomendación es optar por una de estas dos alternativas:
> * Modificar el módulo l10n_co_res_partner, o el que lo vaya a reemplazar, actualizando la lista de valores posibles en el campo tipo select.

@hivam : Doy la misma respuesta que les dio en su momento la OCA (https://github.com/OCA/l10n-colombia/pull/1#issuecomment-227185564), hay muchas características que la OCA ya ha implementado en sus repositorios y nos parece que es desperdiciar un trabajo que está muy bien hecho y a su vez está siendo mantenido por toda la comunidad para todas las versiones liberadas, eso no quiere decir que desperdiciemos el trabajo realizado con el módulo l10n_co_res_partner, que también es un módulo muy bien pensado y hecho, pero no es fácil de mantener, y para la muestra un botón, nosotros aunque no utilizamos este módulo tomamos este módulo como el gran referente para adoptar el consejo de la OCA y en base a lo ya existente en la OCA construimos módulos más pequeños que sólo complementan a los ya existentes. Comparto con ustedes una frase que hay en el mundo del software "¿Por qué reinventar la rueda cuando puedes mejorar el mundo?".

> * Eliminar el campo del módulo l10n_co_res_partner, o el que lo vaya a reemplazar, y agregarlo en el módulo de facturación electrónica

@hivam : Esto realmente si es una opción, pero por ahora, para poder repartirnos el trabajo de lo faltante es más fácil que cada colaborador cree módulos pequeños de requisitos legales que se puedan tratar de forma independiente, otra ventaja de esto, es que si los módulos pequeños van saliendo ahora, se pueden ir instalando, revisando, corrigiendo y configurando para que cuando esté finalizado el módulo de facturación electrónica que obviamente tendría de dependencia todos los módulos pequeños que se desarrollarían en la primera etapa del plan, sea si no realizar pruebas de conexión, y corrección sobre solo esa característica. Y cuando esté el trabajo completado, te aseguro que si seria muy fácil unir todo en un solo modulo si se ve la necesidad.

**Comment by JoanMarin** [comment]
> En Odoo v12 Enterprise el campo se agrega en el módulo Facturación electrónica:
[https://www.odoo.com/documentation/user/12.0/accounting/localizations/colombia.html#configuration](url)
> Ver **4.1.2 Fiscal structure (RUT)**.
> Para el campo **Obligaciones y Responsabilidades** usan el tipo Many2many, así es más fácil de mantener hacia futuro, si la DIAN crea nuevas responsabilidades basta con agregarlas al modelo relacionado sin tener que modificar el código.

Tendremos en cuenta este comentario y estamos totalmente de acuerdo que se debe crear una tabla donde se almacenen las responsabilidades fiscales ya conocidas, y esperando que hayan cambios en el futuro, que estos cambios se puedan realizar desde el sistema y no desde el código del módulo, ya que nos compartes esta documentación, la revisaremos y la tomaremos como parte de nuestras referencias.

**Comment by lauracvilla-zz** [comment]
Hola @hivam  y @JoanMarin 
Considero que para agilizar el aporte colectivo es más fácil distribuir el trabajo a realizar, mientras los módulos se construyen, una vez probado su funcionamiento individual, se puede hacer un trabajo de agrupación en los módulos en la cantidad que se considere es más fácil mantener acorde a las funciones que realicen.

Por ahora nosotros continuaremos revisando el anexo técnico y estableciendo los módulos acorde a los campos y funciones necesarios que hemos identificado.

Que piensas @hivam ? @odooloco/odooloco  han alcanzado a revisar algo?

**Comment by camilozuluaga** [comment]
@JoanMarin una pregunta este campo es un campo nuevo o reemplazar uno existente

**Comment by camilozuluaga** [comment]
Acá esta el módulo nuevo. https://github.com/odooloco/l10n_co_partner_tax_level_code

**Comment by lauracvilla-zz** [comment]
Se sube el módulo ajustado al repositorio
