### ISSUE TITLE
10.0 Construir módulo para manejo de responsable de IVA o no (l10n_co_account_position_list_name)

### ISSUE THREAD

**Issue by lauracvilla-zz** [odoo-colombia/l10n-colombia#5]
En este caso es necesario realizar:

**Nombre Propuesto Módulo:** l10n_co_account_position_list_name

**Campo(s):**

- list_name_id (many2one) | Modelo: account.position.fiscal 
- code (char)  | Modelo: account.position.fiscal.list.name
- name (char)  | Modelo: account.position.fiscal.list.name

**Modelo:** account.position.fiscal

**Información detallada:** Punto 6.2.4 del anexo tecnico DIAN

**Comment by camilozuluaga** [comment]
Buen día, en que parte del menú vamos a poner este módulo y tiene alguna data o simplemente es así y la gente va creando. @JoanMarin

**Comment by JoanMarin** [comment]
@camilozuluaga si lees el punto 6.2.4 del anexo técnico, te daras cuenta que solo son dos valores posibles, la idea es colocarlos en una tabla, porque posiblemente después la dian crea mas tipos, y asi seria mas facil agregarlos.

**Comment by camilozuluaga** [comment]
@JoanMarin en que parte vamos a ubicar el menú para este módulo

**Comment by JoanMarin** [comment]
@camilozuluaga el campo va en la vista de la posición fiscal, no es necesario tener un menú, pero si lo quieres en mi opinión lo ideal es que quede en la zona donde esta el menú de las posiciones fiscales.

**Comment by camilozuluaga** [comment]
Listo el Fork, https://github.com/odooloco/l10n_co_account_position_list_name.

**Comment by lauracvilla-zz** [comment]
Se sube el módulo ajustado al repositorio
