### ISSUE TITLE
10.0 Construir módulo para formas de pago (l10n_co_account_payment_means)

### ISSUE THREAD

**Issue by lauracvilla-zz** [odoo-colombia/l10n-colombia#7]
Se requiere desarrollar el siguiente módulo para el manejo de la información de las formas de pago de la factura

**Nombre Propuesto:**
l10n_co_account_payment_means

**Campos mínimos requeridos descritos a lo largo del anexo para _fe_:**

- [ ] **payment_mean_code_id** (many2one-->account.payment.mean.code) | modelo: account.invoice | Ubicación Anexo: 6.3.4
- [x] **payment_mean_id** (many2one -->account.payment.mean) | modelo: account.invoice | Ubicación Anexo: 6.3.4.1
- [x] **code** (char) | modelo: account.payment.mean.code | Ubicación Anexo: 6.3.4.2
- [x] **name** (char) | modelo: account.payment.mean.code | Ubicación Anexo: 6.3.4.2
- [x] **code** (char) | modelo: account.payment.mean | Ubicación Anexo: 6.3.4.1
- [x] **name** (char) | modelo: account.payment.mean | Ubicación Anexo: 6.3.4.1

**Comment by camilozuluaga** [comment]
https://github.com/camilozuluaga/l10n_co_account_payment_means en este repositorio esta el módulo con los requerimientos

**Comment by JoanMarin** [comment]
@camilozuluaga 

> * [ ]  **payment_means_code_id** (many2one-->account.payment.mean.code) | modelo: account.invoice | Ubicación Anexo: 6.3.4

Todos los campos de este modulo deben ser obligatorios en la vista, solo el campo "payment_means_code_id" tiene una condicion, debe ser obligatorio solo si el estado de la factura es "pago"
> * [ ]  **payment_means_id** (many2one -->account.payment.mean) | modelo: account.payment.mean.code | Ubicación Anexo: 6.3.4.1

El modelo "account.payment.mean.code", debe tener el campo "payment_means_id", este requisito, tal vez si estaba algo enredado, ya que depende de la interpretación, la investigación y el análisis del desarrollador, el punto 6.3.4.2 del anexo nos da la lista de todos los posibles medios de pago identificados para la facturación electrónica, el punto 6.3.4.1 del anexo solo nos establece dos opciones de forma de pago 'credito' o 'contado', acá lo que toca hacer es asignarle a cada uno de los medios de pago, una forma de pago, para saber eso, toca investigar.
> * [x]  **code** (char) | modelo: account.payment.mean.code | Ubicación Anexo: 6.3.4.2
> * [x]  **name** (char) | modelo: account.payment.mean.code | Ubicación Anexo: 6.3.4.2
> * [ ]  **code** (char) | modelo: account.payment.mean | Ubicación Anexo: 6.3.4.1

No se creo el modelo "account.payment.mean" con la data del punto 6.3.4.1 del anexo técnico
> * [ ]  **name** (char) | modelo: account.payment.mean | Ubicación Anexo: 6.3.4.1

No se creo el modelo "account.payment.mean" con la data del punto 6.3.4.1 del anexo tecnico

**Comment by JoanMarin** [comment]
@camilozuluaga te pido perdón, acabo de darme cuenta que me equivoque en algo del requerimiento, el campo (payment_mean_id (many2one -->account.payment.mean) | modelo: account.payment.mean.code | Ubicación Anexo: 6.3.4.1), no va en el modelo account.payment.mean.code, si no en account.invoice, los métodos de pago son independientes de las formas de pago, el campo payment_mean_id debe estar relacionado a una función con **api.onchange** con la fecha de factura y la fecha de vencimiento, si la fecha de vencimiento es igual a la fecha de factura, la forma de pago debió haber sido de contado, si la fecha de vencimiento es mayor a la fecha de la factura, entonces la forma de pago debió haber sido o sera a crédito.

**Comment by JoanMarin** [comment]
Quedo aquí (https://github.com/odooloco/l10n-colombia/tree/10.0/l10n_co_account_invoice_payment_mean) con un pequeño cambio de nombre.

Falta habilitar campo 'payment_mean_code_id' correspondiente al medio de pago, queda pendiente porque hay que analizar si con este campo en tipo 'Many2one', es suficiente para suplir el requerimiento o puede ser necesario establecer un campo One2many ya que la factura podría tener 2 o mas pagos y cada uno podría ser con un medio de pago diferente, o pensar en una solución mas avanzada que este relacionada con el pago de las facturas en Odoo.

**Comment by lauracvilla-zz** [comment]
Se subió el módulo corregido en el repositorio
