### ISSUE TITLE
10.0 Construir módulo para corrección de notas (l10n_co_account_discrepancy_response)

### ISSUE THREAD

**Issue by lauracvilla-zz** [odoo-colombia/l10n-colombia#9]
Se requiere el desarrollo de módulo para la corrección de notas crédito y débito

**Nombre Propuesto:**
l10n_co_account_discrepancy_response

**Campos Requeridos:**
**NP:** type | Modelo: account.invoice.discrepancy.response.code | Sección Anexo: 6.2.5, 6.2.6 |  cac:DiscrepancyResponse/cbc:ResponseCode, out_refund y in_refund
**NP:** code | Modelo: account.invoice.discrepancy.response.code |  Sección Anexo: 6.2.5, 6.2.6 | cac:DiscrepancyResponse/cbc:ResponseCode
**NP:** name | Modelo:  account.invoice.discrepancy.response.code | Sección Anexo:  6.2.5, 6.2.6 | cac:DiscrepancyResponse/cbc:ResponseCode
**NP:** discrepancy_response_code_id | Modelo: account.invoice | Sección Anexo: 6.2.5, 6.2.6 | cac:DiscrepancyResponse/cbc:ResponseCode. Si es in_refund, debe solo permitir escoger opciones de in_refund, si es out_refund, debe solo permitir escoger opciones de out_refund.

**Comment by camilozuluaga** [comment]
@JoanMarin una pregunta. esto es para crear un selection out_refund y in_refund. y lo que esta en las secciones del anexo tecníco va ligado a uno de estos estados. y si es el caso cual seria de out_refounf y in_refound

**Comment by JoanMarin** [comment]
@camilozuluaga 
En el Odoo creo que sabes que hay 4 tipos de facturas:

out_invoice: Factura de venta
out_refund: Factura rectificativa de venta (esto corresponde con el concepto de nota crédito)
in_invoice: Factura de compra
in_refund: Factura rectificativa de compra (esto corresponde con el concepto de nota débito)

Como lo pensé yo, es para solo crear una tabla (account.invoice.discrepancy.response.code) donde este almacena la información de los puntos 6.2.5 (Concepto de Corrección para Notas crédito) y 6.2.6 (Concepto de Corrección para Notas débito), y así no crear dos tablas y dos campos para cada cosa, pero obliga a crear un campo tipo selección (type) en la tabla que identifique de que tipo es el concepto de corrección, yo propongo que los valores de estos tipos sea igual que en la factura (out_refund, in_refund).

discrepancy_response_code_id debe ser un campo obligatorio que solo se debe ver cuando la factura sea de tipo (out_refund, in_refund), pero solo debe poder escoger opciones de la misma característica, si es out_refund solo debe escoger valores de tipo out_refund, y viceversa.

**Comment by camilozuluaga** [comment]
ya quedo el módulo está en esta ruta https://github.com/odooloco/l10n_co_account_discrepancy_response

**Comment by lauracvilla-zz** [comment]
Se sube el módulo corregido al repositorio Odooloco
